name: CrazyEggs
version: '${project.version}'
main: me.choketa.crazyeggs.CrazyEggs
api-version: '1.20'
authors: [Chocketa]
description: Commit crimes with deadly eggs!
commands:
  getegg:
    usage: /getegg <player> amount
    description: Give eggs to a player
    permission: crazyeggs.getegg
    aliases:
      - giveegg
      - obtainegg
  getdestructionegg:
    usage: /getdestructionegg <player> amount
    description: Give eggs to a player
    permission: crazyeggs.getegg
    aliases:
      - givedestructionegg
      - obtaindestructionegg
      - destructionegg
      - destruction
permissions:
  crazyeggs.*:
    description: CrazyEggs wildcard
    children:
      crazyeggs.getegg: true
      crazyeggs.craft: true
      crazyeggs.use: true
      crazyeggs.bypass.cooldown: true
      crazyeggs.destruction.getegg: true
      crazyeggs.destruction.craft: true
      crazyeggs.destruction.use: true
  crazyeggs.getegg:
    description: Allows you to perform the /getegg command
    default: op
  crazyeggs.craft:
    description: Allows you to craft the Crazy Egg
    default: true
  crazyeggs.use:
    description: Allows you to use the Crazy Egg
    default: true


  crazyeggs.destruction.getegg:
      description: Allows you to perform the /getdestructionegg command
      default: op
  crazyeggs.destruction.craft:
      description: Allows you to craft the Destruction Egg
      default: true
  crazyeggs.destruction.use:
      description: Allows you to use the Destruction Egg
      default: true
  crazyeggs.bypass.cooldown:
    description: Allows you to bypass the Destruction's Egg cooldown
    default: op





