name: CrazyEggs
version: '1.2.0'
main: me.choketa.crazyeggs.CrazyEggs
api-version: '1.21'
authors: [Chocketa]
description: Become destructive with crazy eggs!
commands:
  giveegg:
    permission: crazyeggs.getegg
    usage: /giveegg <player> <egg_type> <amount>

permissions:
  crazyeggs.createegg:
    description: Allows you to create eggs
    default: op
  crazyeggs.*:
    description: CrazyEggs wildcard
    children:
      crazyeggs.getegg: true
  crazyeggs.getegg:
    description: Allows you to perform the /getegg command
    default: op




